### ISSUE TITLE
Local Temp deleted

### ISSUE THREAD

**Issue by huliqan** [VRPirates/rookie-pcvr#12]
After run Rookie-PCVR.exe my folder Temp on local disk J:\ in full cleared :(((
How to repair my files in this folder? There been 4Gb my content!(((

**Comment by Fenopy** [comment]
Nothing in the code would clear a folder of any kind.

**Comment by huliqan** [comment]
PCVR-Rookie.exe or Rookie-PCVR.exe create own folder temp,but my folder Temp disappeared along with the contents

**Comment by Chax1** [comment]
It doesnt create its own temp folder
