### ISSUE TITLE
can't connect with 1.4

### ISSUE THREAD

**Issue by ClaireCJS** [VRPirates/rookie-pcvr#13]
Been using this for awhile but dang, 1.4 just won't work.  Changed my DNS to 1.1.1.1 + 8.8.8.8 [i like to mix and match for best odds], turned off antivirus and firewall completely...

![image](https://github.com/VRPirates/rookie-pcvr/assets/789591/f6cc3817-0c8d-470d-bd6d-4d4e333b884f)

Are there log files to figure out what's going wrong?

**Comment by ClaireCJS** [comment]
Also tried running as administrator

**Comment by ClaireCJS** [comment]
``
12:14:44.566 AM (UTC): [INFO] [MainForm..ctor] 
------
------
Program Launched at: 07:14PM(UTC)
------
------

12:14:44.705 AM (UTC): [INFO] [FetchDependencies.downloadFiles] Current RCLONE Version 1.62.2
12:14:44.870 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: listremotes --config vrp.download.config
12:14:45.021 AM (UTC): [INFO] [MainForm.initMirrors] Loaded following mirrors: 
12:14:45.023 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Attempting to Update Download Config
12:14:45.573 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Retrived updated config from: https://vrpirates.wiki/downloads/vrp.download.config
12:14:45.575 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Online Config Hash: d41d8cd98f00b204e9800998ecf8427e; Local Config Hash: d41d8cd98f00b204e9800998ecf8427e
12:14:45.575 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Updated Config Hash matches last download. Not updating.
12:14:45.576 AM (UTC): [INFO] [SideloaderRCLONE.updateUploadConfig] Attempting to Update Upload Config
12:14:45.706 AM (UTC): [INFO] [SideloaderRCLONE.updateUploadConfig] Retrieved updated config from: https://vrpirates.wiki/downloads/vrp.upload.config
12:14:45.706 AM (UTC): [INFO] [SideloaderRCLONE.updateUploadConfig] Upload config updated successfully.
12:14:45.709 AM (UTC): [INFO] [SideloaderRCLONE.initGames] Initializing Games List
12:14:45.709 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:47.913 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:48.100 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:48.254 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:48.498 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:48.694 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:48.860 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.005 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.157 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.314 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.474 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.617 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.779 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:49.932 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:50.106 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:50.256 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:50.396 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:50.569 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:50.728 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:50.915 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:51.118 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:51.297 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:51.441 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:51.588 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:51.739 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:51.898 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:52.060 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:52.199 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config
12:14:52.332 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: cat ":PCVR Games/VRP-GameList.txt" --config vrp.download.config

``

**Comment by Chax1** [comment]
This is not an application issue, but an internet issue. servers are up. use support channels (tg/discord), not git for support.
You can find a link to our Discord/Telegram on our wiki page 🙂

Also, the cat command isn't sus, it's just how rclone works.

**Comment by ClaireCJS** [comment]
(1)

It was definitely an application issue because it failed for all versions of the application in that folder (1.2, 1.3, 1.4) until i nuked the folder and did a clean install, at which point, every version worked.

Whatever happened, it was absolutely the application and not the internet. But a clean install fixed it.

Software developed to the highest standards should leave a log file that says why the failure happened. Clearly your log file was insufficient to identify what absolutely was an application issue, if you have falsely come to the conclusion that my internet was messed up.

But hey, I tried to help you.

Try being more receptive next time and your software will end up less buggy.

**Comment by ClaireCJS** [comment]
(2) Gross mansplaining about 'cat'. Of course that's how rclone works. We know this.

But when trying to debug an APPLICATION error where the program works fine from a clean install but not from the ugpraded folder, i found it sus to see the cat command using file paths that did not include a drive letter before the colon. That's the sus part, in a situation of application failure, which is absolutely what was happening.

But hey, clean install fixed it. If you want to saddle all your users with that instead of fixing bugs, that's your weak prerogative.

**Comment by Chax1** [comment]
Someone had a bad day today...first of all, its not an application issue, and if it is, it's not one in our code, the code works, and it shows that it works because hey, after a clean install everything worked right? 😃 Therefore if there really was bugs in our code you would still face the same issues.
If anything the issue was on your end and on your computer, not on our software side.
Not to mention, to think that this software is "developed to the highest standards" (need I remind you this is run and developed by volunteers) is really entitled and just shows a horrible attitude, if you want to solve our issues, go ahead, you're at our source code so feel free to improve our code you think is so bad! 

Second off, no one is "mansplaining" anything here, the thing rclone is accessing isn't local on your system therefore doesn't have a drive letter because of the way the code works, this isn't some C:/ F:/ D:/ drive. Nor does the file its accessing locally exist on your system, before you try correcting me, read our code first, before mumbling some nonsense because you think you know it all. 

The fact you got angry at being told this isn't an application issue, and had felt the need to write some ragefilled responses instead of maybe going to our live support chats where we can properly help you (mind you, these GitHub issues are supposed to be for actual code issues, not your app not connecting)

Sincerely, keep it to yourself next time, thanks!

**Comment by Chax1** [comment]
FYI! I am not a man, thanks!

**Comment by ClaireCJS** [comment]
It's adorable that you think the code working on a clean install somehow doesn't mean the program failure was an application issue.  That's precious 🤣
