### ISSUE TITLE
had it before

### ISSUE THREAD

**Issue by Minecrafterthebuilder** [VRPirates/rookie-pcvr#16]
i deleted it and redownloaded it put it in the exact same folder in the exact same drive sais that it cant connect to cloud or some shit

**Comment by Chax1** [comment]
This is a connection issue on your end, and not an application problem.
Please use our Support Channels (Telegram or Discord) for support, not Git.

http://t.me/VRPirates

http://discord.gg/DcfEpwVa4a

**Comment by Minecrafterthebuilder** [comment]
> This is a connection issue on your end, and not an application problem. Please use our Support Channels (Telegram or Discord) for support, not Git.
> 
> http://t.me/VRPirates
> 
> http://discord.gg/DcfEpwVa4a

went to the wiki downloaded it there and it worked
