### ISSUE TITLE
Unable to connect to Remote Server. Rookie is unable to connect to our Servers

### ISSUE THREAD

**Issue by CharlesHere0** [VRPirates/rookie-pcvr#6]
![image](https://github.com/VRPirates/rookie-pcvr/assets/112705073/2402ccdf-3df0-4336-8ce4-d19701d967fc)
[debuglog.txt](https://github.com/VRPirates/rookie-pcvr/files/12718316/debuglog.txt)

I have tried everything in the error to try and fix it. I obviously didnt host a mirror though, im pirating games cause im broke.

**Comment by Chax1** [comment]
This is not a program issue but a connection issue.

Use our support channels (which you can find on our wiki) for help on this, not git.
